[tool.poetry]
name = "timetracker"
version = "0.1.0"
description = ""
authors = ["Olaf Gladis <olaf@gladis.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
