[tool.poetry]
name = "timetracker"
version = "0.1.0"
description = ""
authors = ["Olaf Gladis <olaf@gladis.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
rich = "^13.3.1"
typer = "^0.7.0"
pendulum = "^2.1.2"


[tool.poetry.group.dev.dependencies]
pip-audit = "^2.4.14"
pytest = "^7.2.1"
pytest-watch = "^4.2.0"
freezegun = "^1.2.2"
pytest-freezegun = "^0.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
tt = 'timetracker.run:entrypoint'
