[tool.poetry]
name = "timeturner"
version = "0.1.0"
description = ""
authors = ["Olaf Gladis <olaf@gladis.org>"]
readme = "README.md"
packages = [{ include = "timeturner" }]

[tool.poetry.dependencies]
python = "^3.10"
rich = "^13.3.1"
typer = "^0.7.0"
pendulum = "^2.1.2"
pydantic = "^1.10.5"


[tool.poetry.group.dev.dependencies]
pip-audit = "^2.4.14"
pytest = "^7.2.1"
pytest-watch = "^4.2.0"
freezegun = "^1.2.2"
pytest-dependency = "^0.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
timeturner = 'timeturner.run:entrypoint'
